### ISSUE TITLE
floating point exceptions in multiple locations

### ISSUE THREAD

**Issue by project-repo** [knik0/faac#14]
Hi, I was fuzzing faac with afl and I came across some floating point exceptions. One is in lifaac/quantize.c line 367 and the other is in frontend/input.c line 257 (compile with address sanitizer for a more concise backtrace). I will attach the two files causing these errors. (Sorry about the weird file extensions, github won't let me upload the files as .wav)

[err1.txt](https://github.com/knik0/faac/files/1691570/err1.txt)
[err2.txt](https://github.com/knik0/faac/files/1691571/err2.txt)

cheers
project-repo

**Comment by fabiangreffrath** [comment]
@project-repo why did you close this?
