### ISSUE TITLE
Please, tag the releases

### ISSUE THREAD

**Issue by rbrito** [knik0/faac#16]
I saw that you have some commits with comments like "version -> 1.29.9.2". Would it be possible to tag those commits with something like 1.29.9.2? This would be good to use with some tools (including checking automatically if there are new versions).

Thanks,

Rogério.

**Comment by fabiangreffrath** [comment]
I have just pushed tags for all recent releases in the Sourceforge GIT repo, so you will just need to push them here.

https://sourceforge.net/p/faac/faac/

**Comment by knik0** [comment]
Hello,

I had a serious stroke in January and I'm not that well. 
It may take a while before I can do such simple thing. Anyway I will try to look into this.

**Comment by fabiangreffrath** [comment]
This is bad news and I am really sorry to read that. I wish you all the best and hope you are well again soon.

**Comment by fabiangreffrath** [comment]
PS: If you wish you could grant me developer access so I can take care of this janitor work.

**Comment by knik0** [comment]
I just added you to a list of SF admins and github collaborators.
Let me know if it woks for you.

Thanks

**Comment by fabiangreffrath** [comment]
Thank you! I have just pushed the tags to this repo.

**Comment by rbrito** [comment]
Hi, people!

On Sun, Jun 3, 2018 at 9:42 AM, Krzysztof Nikiel
<notifications@github.com> wrote:
> I had a serious stroke in January and I'm not that well.
> It may take a while before I can do such simple thing. Anyway I will try to look into this.

Holy moly, Krzysztof sorry for the late reply, but I just had to give
my words of surprise and, like Fabian, I wish you the very, very, very
best recovery.

While I am ill for some years already, it is not even close to having
a stroke and I sincerely, from the very bottom of my heart, wish you
the best recovery that you can have to be on your top form and to
spread your knowledge, since the world needs more people like you.

Thank you very much,

Rogério.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br
