### ISSUE TITLE
Heavy glitch when encoding with Main/LTP object type

### ISSUE THREAD

**Issue by enzo1982** [knik0/faac#2]
Hi Krzysztof,

Not sure if you are interested in bug reports for Main/LTP encoding. I saw that the code handling the `--obj-type` option is wrapped in an `#if 0` block.

Nevertheless, here is a sample that yields a heavy glitch in the right channel when encoded with either Main or LTP object type and quality set to 100: [sample.zip](https://github.com/knik0/faac/files/1254756/sample.zip)

The glitch is near the end of the sample and only in the right channel - it's easily audible.

Thanks again for resuming work on the FAAC encoder!

Regards,
Robert

**Comment by knik0** [comment]
Hello,

Thanks for testing this. 
A little higher bitrate and worse quality, the whole right channel seems a little choppy.

I was thinking about removing those main/ltp options completely.
Now that it appears broken there's no reason to keep it.

Thanks

**Comment by enzo1982** [comment]
> Now that it appears broken there's no reason to keep it.

Yes, that's what I thought. I'm fine with Main/LTP support being removed completetly.
