### ISSUE TITLE
cppcheck -f -v . 2>cppcheck.log >/dev/null 

### ISSUE THREAD

**Issue by zvezdochiot** [knik0/faac#28]
https://github.com/knik0/faac/blob/40fffb1f696ef1abaf7a0a0ec4c4c3d0cde790b1/common/Cfaac/CRegistry.cpp#L205-L209

Maybe:
```cpp
        BYTE *tempVal=new BYTE[slen];
...
       delete *tempVal;
```
?

https://github.com/knik0/faac/blob/40fffb1f696ef1abaf7a0a0ec4c4c3d0cde790b1/common/Cfaac/CRegistry.cpp#L225-L229

Maybe:
```cpp
...
       delete *tempVal;
```
?

https://github.com/knik0/faac/blob/40fffb1f696ef1abaf7a0a0ec4c4c3d0cde790b1/common/Cfaac/CRegistry.cpp#L343-L345

Maybe:
```cpp
    *dest=NULL;
...
```
?

**Comment by fabiangreffrath** [comment]
What exactly does cppcheck print? It doesn't help if you just post the code lines.

**Comment by zvezdochiot** [comment]
@fabiangreffrath say> What exactly does cppcheck print?

```sh
git/knik0/faac/common/Cfaac$ cat cppcheck.log 
[CRegistry.cpp:209]: (error) Mismatching allocation and deallocation: tempVal
[CRegistry.cpp:229]: (error) Mismatching allocation and deallocation: tempVal
[CRegistry.cpp:345]: (error) Null pointer dereference
```

**Comment by fabiangreffrath** [comment]
In the first two cases, replace `delete tempVal` with `delete[] tempVal`. You are pretty sure right with your fix to the third error.

**Comment by zvezdochiot** [comment]
@fabiangreffrath say> You are pretty sure right with your fix to the third error.

See:
https://github.com/knik0/faac/blob/40fffb1f696ef1abaf7a0a0ec4c4c3d0cde790b1/common/Cfaac/CRegistry.cpp#L317-L320
https://github.com/knik0/faac/blob/40fffb1f696ef1abaf7a0a0ec4c4c3d0cde790b1/common/Cfaac/CRegistry.cpp#L343-L345

**Comment by fabiangreffrath** [comment]
Would you create a PR for this?
