### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by dbn-21** [knik0/faac#49]
Hello
I am getting this error while installing.
can you help?

u0_a257@localhost ~> cd ./faac/
u0_a257@localhost ~/faac (master)> ./bootstrap
configure.ac:17: installing './compile'
configure.ac:19: installing './config.guess'
configure.ac:19: installing './config.sub'
configure.ac:4: installing './install-sh'
configure.ac:4: installing './missing'
frontend/Makefile.am: installing './depcomp'
configure.ac:6: warning: 'AM_CONFIG_HEADER': this macro is obsolete.
configure.ac:6: You should use the 'AC_CONFIG_HEADERS' macro instead.
/home/builder/.termux-build/autoconf/src/lib/autoconf/general.m4:2434: AC_DIAGNOSE is expanded from...
aclocal.m4:9806: AM_CONFIG_HEADER is expanded from...
configure.ac:6: the top level
configure.ac:19: warning: The macro `AM_PROG_LIBTOOL' is obsolete.
configure.ac:19: You should run autoupdate.
aclocal.m4:123: AM_PROG_LIBTOOL is expanded from...
configure.ac:19: the top level
configure.ac:44: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:44: You should run autoupdate.
/home/builder/.termux-build/autoconf/src/lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:44: the top level
configure.ac:53: warning: The macro `AC_HEADER_TIME' is obsolete.
configure.ac:53: You should run autoupdate.
/home/builder/.termux-build/autoconf/src/lib/autoconf/headers.m4:743: AC_HEADER_TIME is expanded from...
configure.ac:53: the top level
configure.ac:61: warning: AC_OUTPUT should be used without arguments.
configure.ac:61: You should run autoupdate.
u0_a257@localhost ~/faac (master)> ./configure
checking for a BSD-compatible install... /data/data/com.termux/files/usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /data/data/com.termux/files/usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3
checking build system type... armv8l-unknown-linux-gnueabi
checking host system type... armv8l-unknown-linux-gnueabi
checking how to print strings... printf
checking for a sed that does not truncate output... /data/data/com.termux/files/usr/bin/sed
checking for grep that handles long lines and -e... /data/data/com.termux/files/usr/bin/grep
checking for egrep... /data/data/com.termux/files/usr/bin/grep -E
checking for fgrep... /data/data/com.termux/files/usr/bin/grep -F
checking for ld used by gcc... /data/data/com.termux/files/usr/bin/ld
checking if the linker (/data/data/com.termux/files/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /data/data/com.termux/files/usr/bin/nm -B
checking the name lister (/data/data/com.termux/files/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 32768
checking how to convert armv8l-unknown-linux-gnueabi file names to armv8l-unknown-linux-gnueabi format... func_convert_file_noop
checking how to convert armv8l-unknown-linux-gnueabi file names to toolchain format... func_convert_file_noop
checking for /data/data/com.termux/files/usr/bin/ld option to reload object files... -r
checking for file... file
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /data/data/com.termux/files/usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /data/data/com.termux/files/usr/bin/dd
checking how to truncate binary pipes... /data/data/com.termux/files/usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for sys/time.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/data/data/com.termux/files/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /data/data/com.termux/files/usr/bin/ld
checking if the linker (/data/data/com.termux/files/usr/bin/ld) is GNU ld... yes
checking whether the g++ linker (/data/data/com.termux/files/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/data/data/com.termux/files/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for getopt.h... yes
checking for immintrin.h... no
checking for gcc options needed to detect all undeclared functions... -fno-builtin
checking whether strcasecmp is declared... yes
checking for getopt_long in -lgnugetopt... no
checking for windres... no
checking whether byte ordering is bigendian... no
checking for egrep... (cached) /data/data/com.termux/files/usr/bin/grep -E
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking for stdint.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for mathf.h... no
checking for float.h... yes
checking whether strchr is declared... yes
checking whether memcpy is declared... yes
checking whether strsep is declared... yes
checking for sys/time.h... (cached) yes
checking for off_t... yes
checking for in_port_t... yes
checking for socklen_t... yes
checking for fpos_t.__pos... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating common/Makefile
config.status: creating libfaac/Makefile
config.status: creating libfaac/faac.pc
config.status: creating frontend/Makefile
config.status: creating include/Makefile
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
u0_a257@localhost ~/faac (master)> make
make  all-recursive
make[1]: Entering directory '/data/data/com.termux/files/home/faac'
Making all in include
make[2]: Entering directory '/data/data/com.termux/files/home/faac/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/data/data/com.termux/files/home/faac/include'
Making all in libfaac
make[2]: Entering directory '/data/data/com.termux/files/home/faac/libfaac'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-bitstream.lo -MD -MP -MF .deps/libfaac_la-bitstream.Tpo -c -o libfaac_la-bitstream.lo `test -f 'bitstream.c' || echo './'`bitstream.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-bitstream.lo -MD -MP -MF .deps/libfaac_la-bitstream.Tpo -c bitstream.c  -fPIC -DPIC -o .libs/libfaac_la-bitstream.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-bitstream.lo -MD -MP -MF .deps/libfaac_la-bitstream.Tpo -c bitstream.c -o libfaac_la-bitstream.o >/dev/null 2>&1
mv -f .deps/libfaac_la-bitstream.Tpo .deps/libfaac_la-bitstream.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-fft.lo -MD -MP -MF .deps/libfaac_la-fft.Tpo -c -o libfaac_la-fft.lo `test -f 'fft.c' || echo './'`fft.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-fft.lo -MD -MP -MF .deps/libfaac_la-fft.Tpo -c fft.c  -fPIC -DPIC -o .libs/libfaac_la-fft.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-fft.lo -MD -MP -MF .deps/libfaac_la-fft.Tpo -c fft.c -o libfaac_la-fft.o >/dev/null 2>&1
mv -f .deps/libfaac_la-fft.Tpo .deps/libfaac_la-fft.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-frame.lo -MD -MP -MF .deps/libfaac_la-frame.Tpo -c -o libfaac_la-frame.lo `test -f 'frame.c' || echo './'`frame.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-frame.lo -MD -MP -MF .deps/libfaac_la-frame.Tpo -c frame.c  -fPIC -DPIC -o .libs/libfaac_la-frame.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-frame.lo -MD -MP -MF .deps/libfaac_la-frame.Tpo -c frame.c -o libfaac_la-frame.o >/dev/null 2>&1
mv -f .deps/libfaac_la-frame.Tpo .deps/libfaac_la-frame.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-blockswitch.lo -MD -MP -MF .deps/libfaac_la-blockswitch.Tpo -c -o libfaac_la-blockswitch.lo `test -f 'blockswitch.c' || echo './'`blockswitch.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-blockswitch.lo -MD -MP -MF .deps/libfaac_la-blockswitch.Tpo -c blockswitch.c  -fPIC -DPIC -o .libs/libfaac_la-blockswitch.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-blockswitch.lo -MD -MP -MF .deps/libfaac_la-blockswitch.Tpo -c blockswitch.c -o libfaac_la-blockswitch.o >/dev/null 2>&1
mv -f .deps/libfaac_la-blockswitch.Tpo .deps/libfaac_la-blockswitch.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-util.lo -MD -MP -MF .deps/libfaac_la-util.Tpo -c -o libfaac_la-util.lo `test -f 'util.c' || echo './'`util.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-util.lo -MD -MP -MF .deps/libfaac_la-util.Tpo -c util.c  -fPIC -DPIC -o .libs/libfaac_la-util.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-util.lo -MD -MP -MF .deps/libfaac_la-util.Tpo -c util.c -o libfaac_la-util.o >/dev/null 2>&1
mv -f .deps/libfaac_la-util.Tpo .deps/libfaac_la-util.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-channels.lo -MD -MP -MF .deps/libfaac_la-channels.Tpo -c -o libfaac_la-channels.lo `test -f 'channels.c' || echo './'`channels.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-channels.lo -MD -MP -MF .deps/libfaac_la-channels.Tpo -c channels.c  -fPIC -DPIC -o .libs/libfaac_la-channels.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-channels.lo -MD -MP -MF .deps/libfaac_la-channels.Tpo -c channels.c -o libfaac_la-channels.o >/dev/null 2>&1
mv -f .deps/libfaac_la-channels.Tpo .deps/libfaac_la-channels.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-filtbank.lo -MD -MP -MF .deps/libfaac_la-filtbank.Tpo -c -o libfaac_la-filtbank.lo `test -f 'filtbank.c' || echo './'`filtbank.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-filtbank.lo -MD -MP -MF .deps/libfaac_la-filtbank.Tpo -c filtbank.c  -fPIC -DPIC -o .libs/libfaac_la-filtbank.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-filtbank.lo -MD -MP -MF .deps/libfaac_la-filtbank.Tpo -c filtbank.c -o libfaac_la-filtbank.o >/dev/null 2>&1
mv -f .deps/libfaac_la-filtbank.Tpo .deps/libfaac_la-filtbank.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-tns.lo -MD -MP -MF .deps/libfaac_la-tns.Tpo -c -o libfaac_la-tns.lo `test -f 'tns.c' || echo './'`tns.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-tns.lo -MD -MP -MF .deps/libfaac_la-tns.Tpo -c tns.c  -fPIC -DPIC -o .libs/libfaac_la-tns.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-tns.lo -MD -MP -MF .deps/libfaac_la-tns.Tpo -c tns.c -o libfaac_la-tns.o >/dev/null 2>&1
mv -f .deps/libfaac_la-tns.Tpo .deps/libfaac_la-tns.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-quantize.lo -MD -MP -MF .deps/libfaac_la-quantize.Tpo -c -o libfaac_la-quantize.lo `test -f 'quantize.c' || echo './'`quantize.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-quantize.lo -MD -MP -MF .deps/libfaac_la-quantize.Tpo -c quantize.c  -fPIC -DPIC -o .libs/libfaac_la-quantize.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-quantize.lo -MD -MP -MF .deps/libfaac_la-quantize.Tpo -c quantize.c -o libfaac_la-quantize.o >/dev/null 2>&1
mv -f .deps/libfaac_la-quantize.Tpo .deps/libfaac_la-quantize.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-huff2.lo -MD -MP -MF .deps/libfaac_la-huff2.Tpo -c -o libfaac_la-huff2.lo `test -f 'huff2.c' || echo './'`huff2.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-huff2.lo -MD -MP -MF .deps/libfaac_la-huff2.Tpo -c huff2.c  -fPIC -DPIC -o .libs/libfaac_la-huff2.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-huff2.lo -MD -MP -MF .deps/libfaac_la-huff2.Tpo -c huff2.c -o libfaac_la-huff2.o >/dev/null 2>&1
mv -f .deps/libfaac_la-huff2.Tpo .deps/libfaac_la-huff2.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-huffdata.lo -MD -MP -MF .deps/libfaac_la-huffdata.Tpo -c -o libfaac_la-huffdata.lo `test -f 'huffdata.c' || echo './'`huffdata.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-huffdata.lo -MD -MP -MF .deps/libfaac_la-huffdata.Tpo -c huffdata.c  -fPIC -DPIC -o .libs/libfaac_la-huffdata.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-huffdata.lo -MD -MP -MF .deps/libfaac_la-huffdata.Tpo -c huffdata.c -o libfaac_la-huffdata.o >/dev/null 2>&1
mv -f .deps/libfaac_la-huffdata.Tpo .deps/libfaac_la-huffdata.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -fvisibility=hidden  -O2 -Wall -fexceptions -MT libfaac_la-stereo.lo -MD -MP -MF .deps/libfaac_la-stereo.Tpo -c -o libfaac_la-stereo.lo `test -f 'stereo.c' || echo './'`stereo.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-stereo.lo -MD -MP -MF .deps/libfaac_la-stereo.Tpo -c stereo.c  -fPIC -DPIC -o .libs/libfaac_la-stereo.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -fvisibility=hidden -O2 -Wall -fexceptions -MT libfaac_la-stereo.lo -MD -MP -MF .deps/libfaac_la-stereo.Tpo -c stereo.c -o libfaac_la-stereo.o >/dev/null 2>&1
mv -f .deps/libfaac_la-stereo.Tpo .deps/libfaac_la-stereo.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fvisibility=hidden  -O2 -Wall -fexceptions -no-undefined   -o libfaac.la -rpath /usr/local/lib libfaac_la-bitstream.lo libfaac_la-fft.lo libfaac_la-frame.lo libfaac_la-blockswitch.lo libfaac_la-util.lo libfaac_la-channels.lo libfaac_la-filtbank.lo libfaac_la-tns.lo libfaac_la-quantize.lo libfaac_la-huff2.lo libfaac_la-huffdata.lo libfaac_la-stereo.lo  -lm
libtool: link: gcc -shared  -fPIC -DPIC  .libs/libfaac_la-bitstream.o .libs/libfaac_la-fft.o .libs/libfaac_la-frame.o .libs/libfaac_la-blockswitch.o .libs/libfaac_la-util.o .libs/libfaac_la-channels.o .libs/libfaac_la-filtbank.o .libs/libfaac_la-tns.o .libs/libfaac_la-quantize.o .libs/libfaac_la-huff2.o .libs/libfaac_la-huffdata.o .libs/libfaac_la-stereo.o   -lm  -O2   -Wl,-soname -Wl,libfaac.so.0 -o .libs/libfaac.so.0.0.0
libtool: link: (cd ".libs" && rm -f "libfaac.so.0" && ln -s "libfaac.so.0.0.0" "libfaac.so.0")
libtool: link: (cd ".libs" && rm -f "libfaac.so" && ln -s "libfaac.so.0.0.0" "libfaac.so")
libtool: link: ar cr .libs/libfaac.a  libfaac_la-bitstream.o libfaac_la-fft.o libfaac_la-frame.o libfaac_la-blockswitch.o libfaac_la-util.o libfaac_la-channels.o libfaac_la-filtbank.o libfaac_la-tns.o libfaac_la-quantize.o libfaac_la-huff2.o libfaac_la-huffdata.o libfaac_la-stereo.o
libtool: link: ranlib .libs/libfaac.a
libtool: link: ( cd ".libs" && rm -f "libfaac.la" && ln -s "../libfaac.la" "libfaac.la" )
make[2]: Leaving directory '/data/data/com.termux/files/home/faac/libfaac'
Making all in common
make[2]: Entering directory '/data/data/com.termux/files/home/faac/common'
make[3]: Entering directory '/data/data/com.termux/files/home/faac/common'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/data/data/com.termux/files/home/faac/common'
make[2]: Leaving directory '/data/data/com.termux/files/home/faac/common'
Making all in frontend
make[2]: Entering directory '/data/data/com.termux/files/home/faac/frontend'
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -I../include   -O2 -Wall -fexceptions -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo input.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -I../include   -O2 -Wall -fexceptions -MT input.o -MD -MP -MF $depbase.Tpo -c -o input.o input.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo mp4write.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -I../include   -O2 -Wall -fexceptions -MT mp4write.o -MD -MP -MF $depbase.Tpo -c -o mp4write.o mp4write.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -O2 -Wall -fexceptions   -o faac main.o input.o mp4write.o ../libfaac/libfaac.la -lm
libtool: link: gcc -O2 -Wall -fexceptions -o .libs/faac main.o input.o mp4write.o  ../libfaac/.libs/libfaac.so -lm -Wl,-rpath -Wl,/usr/local/lib
make[2]: Leaving directory '/data/data/com.termux/files/home/faac/frontend'
make[2]: Entering directory '/data/data/com.termux/files/home/faac'
make[2]: Leaving directory '/data/data/com.termux/files/home/faac'
make[1]: Leaving directory '/data/data/com.termux/files/home/faac'
u0_a257@localhost ~/faac (master)> make install
Making install in include
make[1]: Entering directory '/data/data/com.termux/files/home/faac/include'
make[2]: Entering directory '/data/data/com.termux/files/home/faac/include'
make[2]: Nothing to be done for 'install-exec-am'.
 /data/data/com.termux/files/usr/bin/mkdir -p '/usr/local/include'
mkdir: cannot create directory ‘/usr’: Read-only file system
make[2]: *** [Makefile:335: install-includeHEADERS] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/faac/include'
make[1]: *** [Makefile:452: install-am] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/faac/include'
make: *** [Makefile:399: install-recursive] Error 1
u0_a257@localhost ~/faac (master) [2]>

**Comment by fabiangreffrath** [comment]
> mkdir: cannot create directory ‘/usr’: Read-only file system

Try again as root.

**Comment by dbn-21** [comment]
I wrote it here because I need guidance on this matter.
Can you explain in detail what exactly should someone who cannot do this process do?
step by step what should i do

my device is rooted systemless with magisk

You said try again with root.
what does that mean.?, i'm new to this stuff
Thanks in advance to anyone who is interested and responds.

**Comment by dbn-21** [comment]
I gave root privileges and the result is the same.

If anyone has any advice, I'd be happy to apply it.
I've been trying for a long time and I couldn't make a successful installation.
Thanks

**Comment by dbn-21** [comment]
so I'm going to ask you something
There are some hurdles for me to create in the com.termux directory.
To overcome this obstacle, I would like to do the following.

I will build to mnt/sdcard and copy the generated files to com.termux > usr.

I need help doing this, the lines specifying the installation path, in which directory it is located.

**Comment by dbn-21** [comment]
I understand it better now, thank you.
